# Crimes in india (2001-2012)

### Data Collection/preparation part.

Note: 

collected data from (wiki, google, etc) link is mensioned below from where data is being collected.

Data collected manually.

Dataset includes,

The population of each state.

Literacy Rate in each state

Area of each state


Created a new file and kept the above-collected data seperately

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Cumulative Dataset of Crimes in india.csv")
df

,STATE/UT,YEAR,POPULATION,LITERACY RATE,AREA (in sq. km),MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,...,CRIMES AGAINST CHILDREN,JUVENILES APPREHENDED,POLICEMEN KILLED ON DUTY,THEFT CASES REPOERTED,THEFT VALUE TOTAL,TOTAL Dacoity,TOTAL Robbery,TOTAL Burglary,TOTAL Theft,Human Rights Violation Cases
0,ANDHRA PRADESH,2001,76210007,60.47,275045,2602,1555,136,871,0,...,270.0,3428.0,70.0,24814.0,423123832.0,214.0,629.0,7220.0,16751.0,45
1,ARUNACHAL PRADESH,2001,1097968,54.34,83743,83,53,3,33,0,...,0.0,319.0,1.0,797.0,25830824.0,22.0,84.0,248.0,443.0,11
2,ASSAM,2001,26655528,63.25,78438,1356,481,40,817,0,...,18.0,661.0,34.0,9009.0,91939857.0,532.0,687.0,2423.0,5367.0,35
3,BIHAR,2001,82998509,47.00,94163,3643,3419,250,888,0,...,83.0,1232.0,14.0,16428.0,403558199.0,1291.0,2203.0,3233.0,9701.0,0
4,CHHATTISGARH,2001,20733232,64.66,135191,880,529,45,959,0,...,585.0,2699.0,19.0,9381.0,92027460.0,87.0,338.0,4144.0,4812.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,CHANDIGARH,2012,1144839,86.05,114,21,44,5,27,0,...,96.0,NaN,NaN,1850.0,83472950.0,3.0,63.0,235.0,1549.0,12
404,D & N HAVELI,2012,259148,NaN,491,7,2,0,3,0,...,8.0,NaN,NaN,94.0,13834365.0,2.0,2.0,22.0,68.0,12
405,DAMAN & DIU,2012,191924,NaN,112,3,5,0,5,0,...,8.0,NaN,NaN,85.0,15287800.0,1.0,3.0,26.0,55.0,12
406,LAKSHADWEEP,2012,74578,NaN,32,0,0,0,0,0,...,0.0,NaN,NaN,10.0,279975.0,0.0,0.0,3.0,7.0,12
407,PUDUCHERRY,2012,1148900,NaN,479,29,27,12,13,0,...,32.0,NaN,NaN,756.0,39238036.0,5.0,16.0,77.0,658.0,12

*Data for the population,area of each state and literacy rate of each state have been collected from the different websites manually. 

*The data was available for the year #2001 and #2012 for population, area and literacy rate of each state.

The 15th official census in India was calculated in the year 2011. So, necassary calculations and assumptions were made in order to achive the data for the year #2011  & #2012.

Several websites were used in order to fetch the data for the same. Some of them are:-


https://www.census2011.co.in/
https://mospi.gov.in/sites/default/files/reports_and_publication/cso_research_and_publication_unit/Statistical_Abstract%20_India/2006/sa_06_area_population.pdf
https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate
https://socialjustice.gov.in/common/76669
http://cyberjournalist.org.in/census/cenindia.html
https://www.indiastat.com/specimen-tables/geographical-data
https://www.wbhealth.gov.in/other_files/2007/14_5.html
https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population